# Generated by Django 5.0.4 on 2024-04-21 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_date_joined_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbertimeslot',
            options={'ordering': ['user', 'day_of_week']},
        ),
    ]
