# Generated by Django 5.0.4 on 2024-04-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_barbertimeslot_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123, max_length=13),
            preserve_default=False,
        ),
    ]
