# Generated by Django 5.0.4 on 2024-04-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbertimeslot',
            name='timeslot',
            field=models.CharField(default='000000000000000000000000'),
        ),
    ]
