# Generated by Django 5.0.4 on 2024-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_barbertimeslot_unique_together_user_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbertimeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
