# Generated by Django 2.2.28 on 2024-04-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.IntegerField(choices=[(0, '09:00 - 09:30'), (1, '09:30 - 10:00'), (2, '10:00 - 10:30'), (3, '10:30 - 11:00'), (4, '11:00 - 11:30'), (5, '11:30 - 12:00'), (6, '13:00 - 13:30'), (7, '13:30 - 14:00'), (8, '14:00 - 14:30'), (9, '14:30 - 15:00'), (10, '15:00 - 15:30'), (11, '15:30 - 16:00'), (12, '16:00 - 16:30'), (13, '16:30 - 17:00'), (14, '17:00 - 17:30'), (15, '17:30 - 18:00'), (16, '18:00 - 18:30'), (17, '18:30 - 19:00')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.User')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.User')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
